# Generated by Django 5.1.1 on 2024-10-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Delivered', 'Delivered')], default='Paid', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
