# Generated by Django 5.1.1 on 2024-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mood',
            field=models.CharField(choices=[('MELANCHOLIC', 'Melancholic'), ('WILD', 'Wild'), ('FUNNY', 'Funny'), ('MORALLY_GRAY', 'Morally Gray')], default='MORALLY_GRAY', max_length=50),
        ),
    ]
